name: scanflow
description: "Sistema de control de inventario offline para ScanFlow."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Escaneo de códigos de barras con la cámara.
  mobile_scanner: ^7.4.0
  # Persistencia local 100% offline.
  sqflite: ^2.4.2
  path: ^1.9.0
  # Generación y guardado de PDFs.
  pdf: ^3.11.3
  # Impresión de reportes vía servicios nativos de impresión.
  printing: ^5.15.0
  path_provider: ^2.1.5
  # Compartir el PDF generado con otras apps.
  share_plus: ^13.3.0
  # Alerta sonora al detectar stock bajo / operación.
  audioplayers: ^6.8.1
  # Impresión de etiquetas / tickets a impresoras térmicas Bluetooth.
  print_bluetooth_thermal: ^1.2.2
  # Utilidades para generar los comandos ESC/POS.
  esc_pos_utils_plus: ^2.0.4
  # Selección de impresora Bluetooth cross-platform.
  flutter_blue_plus: ^1.35.5
  # Permisos runtime.
  permission_handler: ^12.0.0
  # Estado simple y ligero para la UI.
  provider: ^6.1.2
  http: ^1.6.0
  ota_update: ^7.1.0
  package_info_plus: ^10.2.1
  sqflite_common_ffi: ^2.4.2+1
  sqlite3_flutter_libs: ^0.6.0+eol

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración del generador de íconos
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/scanflow_logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true